name: upt

on:
  workflow_dispatch:
    
jobs:
    run:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: sudo apt-get update && wget -O java17.deb "https://download.bell-sw.com/java/17.0.4+8/bellsoft-jre17.0.4+8-linux-amd64-full.deb" && sudo apt-get install ./java17.deb -y && ls /usr/lib/jvm
        #sudo update-java-alternatives --set /usr/lib/jvm/bellsoft-java17-runtime-amd64 && java -version
        #"${{ github.event.client_payload.long }}"
      env:
        LINK: ${{secrets.LINK}}
        NAME1: ${{secrets.NAME1}}
        NAME2: ${{secrets.NAME2}}
