name: upt

on:
  workflow_dispatch:
    
jobs:
    run:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: sudo update-java-alternatives --set /usr/lib/jvm/temurin-17-jdk-amd64 && java -jar wget.jar $SECRET1 $SECRET2 "$SECRET3" && java -jar $SECRET4
        #sudo update-java-alternatives --set /usr/lib/jvm/bellsoft-java17-runtime-amd64 && java -version
        #"${{ github.event.client_payload.long }}"
      env:
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
        SECRET3: ${{secrets.SECRET3}}
        SECRET4: ${{secrets.SECRET4}}
