name: upt

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start]
jobs:
    run:
      runs-on: ubuntu-20.04
      timeout-minutes: 70
      steps:
      - uses: actions/checkout@v3
      - name: prepairing and run
        run: bash start.sh
      env:
        SECRET1: ${{secrets.SECRET1}}
        SECRET2: ${{secrets.SECRET2}}
        SECRET3: ${{secrets.SECRET3}}
        SECRET4: ${{secrets.SECRET4}}
        LINK1: ${{secrets.LINK1}}
        LINK2: ${{secrets.LINK2}}
        LINK3: ${{secrets.LINK3}}
